const CONFIG = {
    introTitle: 'Hello anh iu!',
    introDesc: `HAPPY BIRTHDAY MY BABI ^^`,
    btnIntro: 'tiếp nè ^^',
    title: 'Úi có bạn nào đang đọc bức thư này đã bước qua tuổi 18 rồi nè ^^',
    desc: ' Chúc babi có một ngày sinh nhật siêu vui vẻ <3. Chúc dtin qua tuổi mới luôn đẹp zai, học giỏi, có nhiều sức khoẻ nè và thực hiện được những thứ dtin mơ ước nhe, à phải iu em nhìu nữa hì :3 . Cảm ơn dtin vì luôn ở bên cạnh em lúc buồn, luôn nghe em tâm sự. Mong sau này mọi chuyện quan trọng của em đều có sự xuất hiện của anh hihi ^^',
    btnYes: 'iu carrot nhìu nhìu hihi :3',
    btnNo: 'khum iu carrot hic :<',
    question:'Khung điều ước :3',
    btnReply: 'Gửi đi',
    reply: 'Cảm ơn vì đã đến bên em ^^ Love u babi moahh',
    mess: 'Bất ngờ hum hihi :>',
    messDesc: 'Hẹn anh iu hết dịch đi chơi nhee ^^',
    btnAccept: 'oki lun nè',
    messLink: 'https://www.facebook.com/gianghuong0309}
