const CONFIG = {
    introTitle: 'Hello anh iu!',
    introDesc: `Thấy bất ngờ chưa nè hihi`,
    btnIntro: 'hihi',
    title: 'Sắp hết năm 2021 rùi đoáaa',
    desc: ' Hé lu bấy bì, thiệt ra mình ghi cái này cũng lâu gùi mà để cúi năm gửi cho nó có cgi đó gọi là kỉ niệm 2021 é 👉🏻👈🏻 Cảm ơn dtin đã đến và iu thương em, cảm ơn anh đã chịu đựng em những lúc em bị khùm loz, những lúc em làm mình làm mẩy🌚trước khi quen dtin, em chưa muốn tâm sự vs ai về chuyện em giấu, có thể qua đây em có nhiều bạn hơn bên kia nma ngay lúc ấy có nhiều chuyện xảy ra làm em khum thể nào tâm sự dc. Cái điều đó với em nó hông dễ dàng khi mà cố kìm nén cảm xúc trong một thgian dài . Em chỉ hi vọng rằng, sau khi anh đọc xong có thể hiểu cho em, mặc dù thgian qua em có hơi cáu gắt với anh về mọi thứ, lời nói vô tình làm cho anh buồn nma em mong anh có thể giúp em thay đổi điều đó🥲 dtin giúp em làm việc đó dc hén. Cảm ơn bbi vì đã lắng nghe những lời em tâm sự từ trước tới giờ, em hong mún nói trước tại sợ bước hok qa á (nma mong là cùng dc làm trò con bò vs nhau hoài hihi) tui bik là tui cũng hay giấu mấy chuyện buồn lắm nma tui sẽ cố gắng hong giấu ngừi iu nữa đâu hí :> có cgi anh cũng phải lói vs em nhó, đừng coá giấu em 🥺, lâu rùi khum ghi nhìu z hê hê ráng đọc nho moah iu anh 🥰 ',
    btnYes: 'iu carrot nhắm',
    btnNo: 'khum iu carrot',
    question:'Điều mong ước 2022',
    btnReply: 'Gửi đi',
    reply: 'Thank u for everything bấy bì',
    mess: 'Bất ngờ hum hihi :>',
    messDesc: 'Hẹn anh iu hết dịch đi chơi nhee ^^',
    btnAccept: 'oki lun ko đi là kí đầu :>',
    messLink: 'https://www.facebook.com/gianghuong0309}
